[workspace]
resolver = "2"
members = ["corylus-core", "corylus-http-network", "corylus-memory-log"]

[workspace.dependencies]
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
raft = "0.7.0"

axum = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
reqwest = { version = "0.12.14", features = ["json"] }

anyhow = "1.0.97"
thiserror = "2.0.12"
ipnetwork = "0.21.1"
protobuf = "2"

