[package]
name = "corylus-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
raft = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
bincode = { workspace = true }
protobuf =  { workspace = true }
